### ISSUE TITLE
Setup basic extension

### ISSUE THREAD

**Issue by jonathanKingston** [pauljt/lightbeam-we#4]
- Steal existing icon
- Make manifest file
- Make a browser action to create a tab

**Comment by princiya** [comment]
This is what I created as part of my application process to Outreachy: https://github.com/princiya/log-network-requests
A simple web extension

**Comment by biancadanforth** [comment]
Thanks Princiya! Yes I made [one](https://github.com/biancadanforth/network-requests-webext) too, and I have [Jonathan](https://github.com/jonathanKingston/extension-debugging)'s as a reference as well. No shortage of resources on this front, heh.
